# Generated by Django 4.2.1 on 2023-09-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiTabla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rbo', models.CharField(max_length=250)),
                ('info_rbo', models.CharField(max_length=250)),
                ('fechas', models.DateTimeField()),
            ],
            options={
                'db_table': 'robdb',
            },
        ),
    ]
